### ISSUE TITLE
NoClassDefFoundException

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#10]
On loading the latest build, I am getting  NoClassDefFoundException on load in PailInterface.
java.lang.NoClassDefFoundError: me/iffa/bananaspace/gui/PailInterface$12
        at me.iffa.bananaspace.gui.PailInterface.initComponents(PailInterface.java:334)
        at me.iffa.bananaspace.gui.PailInterface.<init>(PailInterface.java:33)
        at me.iffa.bananaspace.BananaSpace.onEnable(BananaSpace.java:136)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:885)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassNotFoundException: me.iffa.bananaspace.gui.PailInterface$12
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more

**Comment by iffa** [comment]
Weird

**Comment by kitskub** [comment]
Latest build fixes this. I have no clue what it was.
**EDIT**This is not true.

**Comment by kitskub** [comment]
Seems like this issue causes another issue when referring to the PailInterface
