### ISSUE TITLE
bSpace breaks Everytime the server goes down for maintainance.

### ISSUE THREAD

**Issue by modtv1337** [kitskub/bSpace#110]
Not sure exactly where this issue originates so i will start by posting it here. Everytime the server is (Safely) shut down ie the /stop command is issued upon restarting the server an error appears and the server no longer recognizes the map.
i was on bukkit 1.2.5R1.0 and found that upgrading to 1.2.5R1.2 Gave me the same issues.

2012-04-25 01:10:31 [INFO] [Multiverse-Core] Enabling Multiverse-Core v2.4-b527
2012-04-25 01:10:31 [INFO] [Multiverse-Core] - Version 2.4-b527 (API v14) Enabled - By Rigby, fernferret, lithium3141 and main--
2012-04-25 01:10:31 [INFO] [AllPay] - Version 10.0 - hooked into iConomy 6 for Multiverse-Core v2.4-b527
2012-04-25 01:10:31 [INFO] [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: NORMAL & seed: -72305783100051629
2012-04-25 01:10:31 [INFO] [Multiverse-Core] Loading World & Settings - 'world_nether' - Env: NETHER - Type: NORMAL & seed: -72305783100051629
2012-04-25 01:10:31 [INFO] [Multiverse-Core] Loading World & Settings - 'world_the_end' - Env: THE_END - Type: NORMAL & seed: -72305783100051629
2012-04-25 01:10:31 [SEVERE] Error occurred while enabling Multiverse-Core v2.4-b527 (Is it up to date?)
java.lang.NullPointerException
    at me.iffa.bspace.api.SpaceWorldHandler.getID(SpaceWorldHandler.java:154)
    at me.iffa.bspace.api.SpaceConfigHandler.getID(SpaceConfigHandler.java:42)
    at me.iffa.bspace.api.SpaceWorldHandler.addSpaceWorld(SpaceWorldHandler.java:163)
    at me.iffa.bspace.api.SpaceWorldHandler.checkWorld(SpaceWorldHandler.java:149)
    at me.iffa.bspace.Space.getDefaultWorldGenerator(Space.java:206)
    at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:284)
    at org.bukkit.WorldCreator.generator(WorldCreator.java:181)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:113)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:91)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:557)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:242)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by kitskub** [comment]
Hmm, this problem can be easily fixed. Probably a change with bukkit, or mutliverse has caused this.

**Comment by modtv1337** [comment]
That is good to hear, Where should i go to look out for a revised version of this amazing generator?

**Comment by kitskub** [comment]
Done! https://github.com/iffa/bSpace/blob/master/target/bSpace-v2.3.jar

**Comment by modtv1337** [comment]
You sir earn Free advertisement on my site.
Fast fix with link someone give this guy a prize

**Comment by modtv1337** [comment]
btw how do i compile this XD i feel so noob

**Comment by kitskub** [comment]
It is compiled. The link is a download link. I would give you a jenkins link, but it's down right now.

**Comment by modtv1337** [comment]
ahh Thanks again you made my day

**Comment by kitskub** [comment]
You are quite welcome.

**Comment by modtv1337** [comment]
btw i generated a world and was met with this spamming my console im sure its nothing too major and might not pop up but im passing this along just incase XD 

http://pastebin.com/SUtdB35Q

**Comment by modtv1337** [comment]
nvm disregard issue :) i fixed it by deleting my essentials database :)
