### ISSUE TITLE
Internal Error when using /space enter

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#13]
When using /space enter, you get an internal error. This is only true if you do not specify the name of the space world.

**Comment by iffa** [comment]
What's the error in the log?

**Comment by kitskub** [comment]
org.bukkit.command.CommandException: Unhandled exception executing command 'space' in plugin BananaSp
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:352)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:737)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:436)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.RangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at me.iffa.bananaspace.commands.SpaceCommand.onCommand(SpaceCommand.java:71)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
        ... 13 more
