### ISSUE TITLE
New Config giving some errors

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#55]
I was about to get off, when I decided to do a test check on the new code. This popped up, in to spots... But I can't fix it now...

java.lang.NullPointerException
        at me.iffa.bananaspace.config.SpaceConfig.getConfig(SpaceConfig.java:45)
        at me.iffa.bananaspace.api.SpaceConfigHandler.getDebugging(SpaceConfigHandler.java:25)
        at me.iffa.bananaspace.api.SpaceMessageHandler.debugPrint(SpaceMessageHandler.java:39)
        at me.iffa.bananaspace.BananaSpace.getDefaultWorldGenerator(BananaSpace.java:188)
        at com.onarandombox.utils.WorldManager.getChunkGenerator(WorldManager.java:146)
        at com.onarandombox.utils.WorldManager.addWorld(WorldManager.java:77)
        at com.onarandombox.utils.WorldManager.loadWorlds(WorldManager.java:384)
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:137)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:174)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)

**Comment by iffa** [comment]
NPe @ 45? alright

**Comment by iffa** [comment]
That could be because the boolean is not in there
which is of course annoying, i fixed

**Comment by iffa** [comment]
^ Which was because there were no .put(configfile, false) in load

**Comment by kitskub** [comment]
It's still kind of funny... I'm checking it out now.

**Comment by iffa** [comment]
Fixed?
