### ISSUE TITLE
Crash on CB 1550 while /space enter

### ISSUE THREAD

**Issue by 7eggert** [kitskub/bSpace#75]
Server version git-Bukkit-1.8.1-R4-77-ge86a355-b1550jnks
bSpace version v2-dev (2011-12-04)
Multiverse version 2011-12-02

02:53:08 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'space' in plugin bSpace vv2-dev
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:370)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerTeleportEvent$TeleportCause
        at me.iffa.bspace.commands.SpaceEnterCommand.command(SpaceEnterCommand.java:73)
        at me.iffa.bspace.commands.SpaceCommand.<init>(SpaceCommand.java:32)
        at me.iffa.bspace.commands.SpaceEnterCommand.<init>(SpaceEnterCommand.java:41)
        at me.iffa.bspace.commands.SpaceCommandHandler.onCommand(SpaceCommandHandler.java:61)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerTeleportEvent$TeleportCause
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 17 more

**Comment by kitskub** [comment]
Please use at least build 1551. That should fix it. Oh, and thank you for all the info. Really helped when finding the problem
