### ISSUE TITLE
Multiverse not generating BananaSpace

### ISSUE THREAD

**Issue by kripts** [kitskub/bSpace#76]
2011-12-07 20:50:46 [INFO] [BananaSpace] Plugin 'BananaSpace' starting to create spaceworld 'space'
2011-12-07 20:50:46 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvc' in plugin Multiverse-Core v2.1-b326
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:372)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.NullPointerException
    at me.iffa.bananaspace.api.SpaceWorldHandler.createSpaceWorld(SpaceWorldHandler.java:154)
    at me.iffa.bananaspace.BananaSpace.getDefaultWorldGenerator(BananaSpace.java:184)
    at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:240)
    at org.bukkit.WorldCreator.generator(WorldCreator.java:158)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:66)
    at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:65)
    at com.pneumaticraft.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:245)
    at com.pneumaticraft.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:115)
    at com.pneumaticraft.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:70)
    at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:406)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by iffa** [comment]
I assume this is v1.4_2? If so, I suggest you use a build of v2, seeing that you want to use Multiverse to generate. Link to jenkins is in readme

**Comment by kripts** [comment]
I downloaded v2 and still couldnt generate but this time it allowed me to access the /space commands everytime i try import with /mvc Space normal -g bSpace it gives me a "An internal error occurred while attempting to perdorm this command" I also tried manually adding the generator in the multiverse worlds.yml file still no luck :( any advice into how to solve this?
Thanks for your replies

**Comment by kitskub** [comment]
When you get the error, can you post your log? What CraftBukkit version are you using?

**Comment by kripts** [comment]
log is above and git-Bukkit-1.8.1-R4-93-ged6232b-b1565jnks (MC: 1.0.1) (Implementing API version 1.0.0-R1-SNAPSHOT)

**Comment by kitskub** [comment]
Is the log for v2?

**Comment by kripts** [comment]
No sorry, this is:

org.bukkit.command.CommandException: Unhandled exception executing command 'mvc' in plugin Multiverse-Core v2.1-b326
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:374)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:521)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.NullPointerException
    at me.iffa.bspace.Space.getDefaultWorldGenerator(Space.java:221)
    at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:240)
    at org.bukkit.WorldCreator.generator(WorldCreator.java:158)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:66)
    at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:65)
    at com.pneumaticraft.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:245)
    at com.pneumaticraft.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:115)
    at com.pneumaticraft.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:70)
    at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:406)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by kitskub** [comment]
Ok, are you using the most recent version of v2? Sorry, but because there has been a LOT of changes, its hard to pinpoint the problem unless all the version stuff is known...

**Comment by kitskub** [comment]
I believe I know the problem

**Comment by kripts** [comment]
I tried the last few releases, what do I do with that kitskub? Thanks for all your help guys

**Comment by kitskub** [comment]
Check the target directory HERE, on github. I made a change that might fix it, but Jenkins won't clone the repo...

**Comment by kripts** [comment]
The generator did not fail this time, but it didn't create a config, im just trying to get the config from the other version ill get back to you soon

**Comment by kripts** [comment]
Using the old Config it didn't work, same error as before, heres the logs:

org.bukkit.command.CommandException: Unhandled exception executing command 'mvc' in plugin Multiverse-Core v2.1-b326
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:374)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:521)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.NullPointerException
    at me.iffa.bspace.Space.getDefaultWorldGenerator(Space.java:206)
    at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:240)
    at org.bukkit.WorldCreator.generator(WorldCreator.java:158)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:66)
    at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:65)
    at com.pneumaticraft.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:245)
    at com.pneumaticraft.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:115)
    at com.pneumaticraft.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:70)
    at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:406)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by kitskub** [comment]
Of course, I see now... fixed, try again

**Comment by kitskub** [comment]
That wasn't supossed to close...

**Comment by kripts** [comment]
I can confirm that you are a genius, It worked! Thankyou for all your time and effort in fixing the problem :)

**Comment by kitskub** [comment]
No problem.

**Comment by kitskub** [comment]
Oh, and by the way. That problem would have probably occured a lot. Especially considering the fact it would happen every time no id is specified...which could be a lot.
